### ISSUE TITLE
margin collapsing with "clearfix" fallback

### ISSUE THREAD

**Issue by revyh** [fliptheweb/postcss-flow-root#3]
`flow-root` creates new BFC on element, wich prevent margins of children elements from "leaking". `column-count` and `overflow` fallbacks also creates new BFC, so there is no problems with them. But `clearfix` fallback doesn't create new BFC and `margin-top` "leaks" from children elements.

[Here](http://codepen.io/revyh/pen/rygVdN) is the simple pen that illustrates this issue.

If we want to be closer to spec, than we should replace clearfix from
```css
.clearfix::after {
  content: '';
  display: table;
  clear: both;
}
```

 to

```css
.clearfix::before,
.clearfix::after {
  content: '';
  display: table;
}

.clearfix::after {
  clear: both;
}
```

**Comment by OliverJAsh** [comment]
@revyh 

Does your second example have any trade offs? Seems to work over here—creates a new BFC and disables margin collapsing.

**Comment by revyh** [comment]
@OliverJAsh I don't clearly understand what do you mean by "second example" and "trade offs". I suggest, that you compare second code snippet in this issue with browser implementation of `flow-root`.

If so, then main trade off is that clearfix doesn't really creates new BFC (more on this in [another issue](https://github.com/fliptheweb/postcss-flow-root/issues/2)). If you want to use `flow-root` only as a modern clearfix, then you may don't care about BFC. But there is always be the small chance to break your layout when you switch from this plugin to browser implementation.

**Comment by OliverJAsh** [comment]
As you have pointed out, the currently used `clearfix` does not prevent margin collapsing:

```
.clearfix::after {
  content: '';
  display: table;
  clear: both;
}
```

However, margin collapsing can be prevented by switching this to use the `::before` pseudo element instead:

http://output.jsbin.com/poquxa/3

I wonder if there are any drawbacks to using this alternative clearfix?

I was considering using `column-count: 1`, however there are drawbacks when using absolutely positioned items within:

- https://bugs.chromium.org/p/chromium/issues/detail?id=780733
- http://jsbin.com/bexewig/4

**Comment by OliverJAsh** [comment]
In fact this seems to work as well:

``` css
  .clearfix::before,
  .clearfix::after {
    content: '';
    display: table;
  }
```

https://codepen.io/OliverJAsh/pen/pdjGrW
