### ISSUE TITLE
"display: block" fallback

### ISSUE THREAD

**Issue by revyh** [fliptheweb/postcss-flow-root#4]
It's not another one fallback option like `column-count`, `overflow` or `clearfix`. Spec defines `flow-root` as `display: block` + new BFC. And `display: block` part is missed for now. It allows cases like this:

```css
/* before */
span {
  display: flow-root;
}

/* after "clearfix" fallback */
span {
  /* if browser doesn't support "flow-root" than "display" will actually have "inline" value, which will mess with pseudo elements */
  display: flow-root;
}

span::after {
  content: '';
  display: table;
  clear: both;
}
```

Instead it should be transformed like this:

```css
/* after "clearfix" fallback */
span {
  display: block;
  display: flow-root;
}

span::after {...}
```
